### ISSUE TITLE
Docs should include something about having multiple sliders in one page. 

### ISSUE THREAD

**Issue by dennislzf** [mobify/scooch#31]
Docs should include whether you need to initialize scooch 3 times on 3 separate class names, or just once on one class name

**Comment by tedtate** [comment]
@dennislzf can you expand on this a little bit more?

I think the docs meet my expectation as a user as they are currently written. If you do something like `$('.scooch').scooch();` I would expect that this initializes scooch for all DOM nodes which have the `scooch` class name.
