### ISSUE TITLE
Circular Loop

### ISSUE THREAD

**Issue by prijindal** [mobify/scooch#37]
Is there a way to make it loop, so that after last item, first item is there

**Comment by ericalas93** [comment]
Been working on the something to make this possible, just doing some testing and will commit after christmas :)

**Comment by christopher-s** [comment]
@ericalas93: Are you planning on doing a pull request to get this circular loop adjustment in place?
That would be great if you can. Thanks.

**Comment by ericalas93** [comment]
Hi there, yup I've made a pull request! I mean it appears on my end that
the master branch has a pull request of mine? Thanks!

On Sat, Jan 9, 2016 at 2:54 PM, Christopher Staley <notifications@github.com

**Comment by marlowpayne** [comment]
Hi @ericalas93 thanks for the contribution! We will be including an infinite-looping option for Scooch as part of the [v1.0.0 release](https://github.com/mobify/scooch/pull/39).

**Comment by marlowpayne** [comment]
Interesting that this issue didn't auto-close as expected. Closing off now.
