### ISSUE TITLE
autoplay

### ISSUE THREAD

**Issue by 2silver** [mobify/scooch#5]
Add "auto" Play Feature

**Comment by per-ludum** [comment]
+1

**Comment by ericmuyser** [comment]
+1

Until that's added though, this snippet should work:

```js
    var $scooch = $('.scooch');
    var scooch = $scooch.scooch()[0]._scooch;

    function autoRotate() {
        var currentIndex = scooch._index;
        var length = scooch._length;

        if(currentIndex == length) {
            currentIndex = 0;
        }

        $scooch.scooch('move', currentIndex + 1);

        setTimeout(autoRotate, 150);
    }

    setTimeout(autoRotate, 150);
```

**Comment by per-ludum** [comment]
Thanks a lot for this code, which works nicely!

The latest article about sliders (and mobifys approach) on smashingmag* made me discover the scooch slider last week, which is absolutely fantastic. It’s light, fast, zepto enabled and the navigation is configurable via html. 

The article also changed my mind about the autoplay feature. But in some cases it’s hard to abandon it. So I would really appreciate if this little feature would be added to scooch, with a mouseover-stop. 

Thanks for the awesome slider!

*http://www.smashingmagazine.com/2015/02/09/carousel-usage-exploration-on-mobile-e-commerce-websites/

**Comment by kpeatt** [comment]
@per-ludum Glad you like it and thanks for your feedback!
